require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'UnicodeProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  target 'UnicodeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'UnicodeProject-tvOS' do
  # Pods for UnicodeProject-tvOS

  target 'UnicodeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
